### PR TITLE
58 workflow state model

### PR DESCRIPTION
**Pull request by emilytoppm**
- Adds WorkflowState and TaskState models
- Adds methods for approving and rejecting states, and for a WorkflowState to be progressed
- Adds tests for workflow progression
- Adds configurable action for successful workflow finish
- Adds start methods to Workflow and Task to create WorkflowState and TaskState instances respectively

### CODE REVIEW

**Comment by gasman** [comment]
Hi @jacobtoppm - please can you rebase this on top of the current workflow-base branch (which should just leave the last 4 commits), and revert the unrelated formatting changes on wagtail/core/models.py?

**Comment by emilytoppm** [comment]
> Hi @jacobtoppm - please can you rebase this on top of the current workflow-base branch (which should just leave the last 4 commits), and revert the unrelated formatting changes on wagtail/core/models.py?

@gasman - Sorry about that, I'd missed adding those. Done now, hope that's a bit better!

**Review by gasman — APPROVED** [review]
Looks good to me!

Just one nitpick about the placement of the `publish_workflow_state` function - I think it's a bit too 'single-purpose' to belong in a utils module. (Utils modules are an anti-pattern at the best of times - they end up as a dumping ground for code that hasn't been organised better...) I'd suggest putting this in a new `wagtail.core.workflows` module - I suspect it's not going to be the only thing that belongs in that namespace!

**Comment by emilytoppm** [comment]
> Looks good to me!
> 
> Just one nitpick about the placement of the `publish_workflow_state` function - I think it's a bit too 'single-purpose' to belong in a utils module. (Utils modules are an anti-pattern at the best of times - they end up as a dumping ground for code that hasn't been organised better...) I'd suggest putting this in a new `wagtail.core.workflows` module - I suspect it's not going to be the only thing that belongs in that namespace!

Thanks for reviewing! That's a good point - it did seem a bit single purpose when I was putting it in there, a workflows module definitely seems like a better place. I've moved in the latest commit.

**Pull request merged**
